name: Dart CI

on:

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
    - name: Install dependencies
      run: flutter pub get
    - name: flutter tests
      run: flutter test
